<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class File extends Model
{
    protected $guarded = ['id'];
    public $timestamps = false;

    public function morphTo($name = null, $type = null, $id = null, $ownerKey = null)
    {
        return $this->morphTo();
    }

    public function delete()
    {
        if(file_exists(\Storage::disk('public')->path($this->url))){
            @unlink(\Storage::disk('public')->path($this->url));
        }
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
