<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Image extends Model
{
    protected $guarded = ['id'];
    public $timestamps = false;

    public function removeFile()
    {
        if(file_exists(\Storage::disk('public')->path($this->url))){
            @unlink(\Storage::disk('public')->path($this->url));
        }
    }

    public function delete()
    {
        $this->removeFile();
        return parent::delete(); // TODO: Change the autogenerated stub
    }

    public function file()
    {
        return $this->belongsTo(File::class);
    }
}
